// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetoCoreEFtoPostgres.context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NetoCoreEFtoPostgres.Migrations
{
    [DbContext(typeof(SomethingContext))]
    [Migration("20210508112044_addChildRecord")]
    partial class addChildRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.ChildSomethingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SomethingModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Subsidiary")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SomethingModelId");

                    b.ToTable("ChildSomethingModel");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.SomethingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subsidiary")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Somethings");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.ChildSomethingModel", b =>
                {
                    b.HasOne("NetoCoreEFtoPostgres.Entities.SomethingModel", null)
                        .WithMany("childs")
                        .HasForeignKey("SomethingModelId");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.SomethingModel", b =>
                {
                    b.Navigation("childs");
                });
#pragma warning restore 612, 618
        }
    }
}
