// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetoCoreEFtoPostgres.context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NetoCoreEFtoPostgres.Migrations
{
    [DbContext(typeof(SomethingContext))]
    partial class SomethingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.ChildSomethingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("HeadModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subsidiary")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeadModelId");

                    b.ToTable("ChildSomethingModel");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.SomethingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subsidiary")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Somethings");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.ChildSomethingModel", b =>
                {
                    b.HasOne("NetoCoreEFtoPostgres.Entities.SomethingModel", "HeadModel")
                        .WithMany("childs")
                        .HasForeignKey("HeadModelId");

                    b.Navigation("HeadModel");
                });

            modelBuilder.Entity("NetoCoreEFtoPostgres.Entities.SomethingModel", b =>
                {
                    b.Navigation("childs");
                });
#pragma warning restore 612, 618
        }
    }
}
